export const AUTHORS: [string, string][] = [
  ['Jane', 'AUSTEN'],
  ['Mark', 'TWAIN'],
  ['Ernest', 'HEMINGWAY'],
  ['Virginia', 'WOOLF'],
  ['Charles', 'DICKENS'],
  ['Maya', 'ANGELOU'],
  ['George', 'ORWELL'],
  ['Toni', 'MORRISON'],
  ['Oscar', 'WILDE'],
  ['Emily', 'DICKINSON'],
  ['Leo', 'TOLSTOY'],
  ['Agatha', 'CHRISTIE'],
  ['Franz', 'KAFKA'],
  ['Sylvia', 'PLATH'],
  ['Haruki', 'MURAKAMI'],
  ['Margaret', 'ATWOOD'],
  ['James', 'BALDWIN'],
  ['Fyodor', 'DOSTOEVSKY'],
  ['Ralph', 'ELLISON'],
  ['Kurt', 'VONNEGUT'],
  ['Octavia', 'BUTLER'],
  ['Albert', 'CAMUS'],
  ['Zadie', 'SMITH'],
  ['Ray', 'BRADBURY'],
  ['Isabel', 'ALLENDE'],
  ['Neil', 'GAIMAN'],
  ['Kazuo', 'ISHIGURO'],
  ['Langston', 'HUGHES'],
  ['Lewis', 'CARROLL'],
  ['Alice', 'WALKER'],
  ['Herman', 'MELVILLE'],
  ['Louisa', 'ALCOTT'],
  ['Edgar', 'POE'],
  ['Charlotte', 'BRONTË'],
  ['Pablo', 'NERUDA'],
  ['Chinua', 'ACHEBE'],
  ['Aldous', 'HUXLEY'],
  ['Anton', 'CHEKHOV'],
  ['Willa', 'CATHER'],
  ['James', 'JOYCE'],
  ['Beatrix', 'POTTER'],
  ['Italo', 'CALVINO'],
  ['Clarice', 'LISPECTOR'],
  ['Jorge', 'BORGES'],
  ['Daphne', 'DU MAURIER'],
  ['Zora', 'HURSTON'],
  ['Ursula', 'LE GUIN'],
  ['Chimamanda', 'ADICHIE'],
  ['Gabriel', 'GARCÍA MÁRQUEZ'],
  ['Flannery', "O'CONNOR"],
];

export function getRandomAuthor(): [string, string] {
  return AUTHORS[Math.floor(Math.random() * AUTHORS.length)];
}
